In [1]:
import numpy as np
#importing numpy repository

In [3]:
z=[1,2,3]
np.array(z)

array([1, 2, 3])

In [4]:
q=[[1,2,3],[4,5,6],[7,8,9]]
np.array(q)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.linspace(0,20,10)
#evenly spaced values between 0 & 20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [20]:
np.random.randn(5,5)

#random values in 5x5 matrix

array([[ 1.37548   ,  0.45785332, -0.96354431, -0.60271542, -0.52141231],
       [-1.00866209, -1.03816975,  0.24010976, -0.7347658 ,  0.84418138],
       [ 0.24441383,  0.99789016,  0.17394074,  1.11216335, -0.35729686],
       [-1.15077359, -0.73439603,  0.31054588, -1.48003693, -0.71978574],
       [-1.54519403, -1.29123927, -1.24952484, -0.31232895, -0.05321803]])

In [21]:
x=np.random.randint
x(10,100,10)

#random intergers between 10 & 100

array([82, 78, 70, 76, 42, 16, 11, 17, 60, 55])

In [24]:
#Creating sample array
v=np.arange(0,11)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
#Get values in a range
v[0:5]

array([0, 1, 2, 3, 4])

In [29]:
#Boolean
v>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [30]:
#Indexing 2D arrays
b = np.array(([5,10,15],[20,25,30],[35,40,45]))
b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
b[1]

array([20, 25, 30])

In [32]:
b[1][2]

30

In [39]:
#Fancy Indexing
d=np.zeros((10,10))
d_length = d.shape[1]

for i in range(d_length):
    d[i] = i
    
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])