In [2]:
import numpy as np
#importing numpy repository

In [3]:
z=[1,2,3]
np.array(z)

array([1, 2, 3])

In [4]:
q=[[1,2,3],[4,5,6],[7,8,9]]
np.array(q)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.linspace(0,20,10)
#evenly spaced values between 0 & 20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [6]:
np.random.randn(5,5)

#random values in 5x5 matrix

array([[ 0.33775759, -0.43832548,  0.05572199,  0.85655083,  0.31199914],
       [-0.61194391, -1.00600462, -0.25819831,  0.54087867, -2.08927277],
       [-1.53210507,  0.97121071,  0.38778891, -0.55578422,  0.3356674 ],
       [-0.12338746,  0.07266157,  0.50800219,  1.43701146,  0.72240385],
       [-0.70233784,  1.61207739, -0.43547595,  0.58122677,  1.86701502]])

In [7]:
x=np.random.randint
x(10,100,10)

#random intergers between 10 & 100

array([62, 37, 73, 20, 73, 20, 58, 90, 50, 87])

In [8]:
#Creating sample array
v=np.arange(0,11)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#Get values in a range
v[0:5]

array([0, 1, 2, 3, 4])

In [29]:
#Boolean
v>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [30]:
#Indexing 2D arrays
b = np.array(([5,10,15],[20,25,30],[35,40,45]))
b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
b[1]

array([20, 25, 30])

In [32]:
b[1][2]

30

In [39]:
#Fancy Indexing
d=np.zeros((10,10))
d_length = d.shape[1]

for i in range(d_length):
    d[i] = i
    
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [22]:
a=np.array(([5,10,15],[20,25,30],[35,40,45]))
a

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [1]:
b=np.array(([6,20,40],[15,55,25],[33,12,43]))
b

NameError: name 'np' is not defined

In [25]:
np.mean(b != a)

1.0

In [27]:
x=[]
x.append(np.mean(b != a))

In [36]:
np.eye(3) * 3

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [1]:
a = 0
>>> while (a:=a+1) < 5:
    print(a)

1
2
3
4
